### ISSUE TITLE
using Critter from Gradle

### ISSUE THREAD

**Issue by amiracam** [MorphiaOrg/critter#15]
is there a gradle plugin for Critter ? if so pls share coordinates and will that suffice to make IDEA "intellisense" aware of the critter generated specs i.e. is there something else one needs to do to configure Idea in the context of gradle/critter

thanks

**Comment by evanchooly** [comment]
There is/used to be but it's been ignored because I don't use gradle and haven't had any one ask in a  while.  But i can certainly revive it.  It should take too much I don't think.

**Comment by amiracam** [comment]
it would be very much appreciated it, Morphia is proving quite useful and Critter would just make it even nicer and we do everything with Gradle, much thanks

**Comment by evanchooly** [comment]
That's great to hear.  I'll make it a priority.

**Comment by evanchooly** [comment]
OK.  that took me *way* longer than I expected.  but i have a working plugin again.  if you want to try the snapshot build there's a `4.1.0-SNAPSHOT` build that should be available now.  I need to write some documentation and test a few config items that seem broken atm (`criteriaPackage`) but unless you want to change what package is used, you should be good to at least give it a try.  Aslo, i'm not a gradle user so some feedback from an actual gradle type would help round things out.  Thanks for your patience.

**Comment by evanchooly** [comment]
docs have been updated

**Comment by KernelFreeze** [comment]
Is it available on some plugin repository?

**Comment by evanchooly** [comment]
Silly me.  I thought i'd pushed a release with that but clearly hadn't.  I pushed one just now and it has finished syncing to maven central.  You can find the docs at https://morphia.dev.

**Comment by KernelFreeze** [comment]
Great, thank you!
